import type {
  BonusProject,
  CksMonth,
  DemoUser,
  Employee,
  PayrollInput,
  PayslipPublish,
  SelfReview,
} from "@/types/hr"

export const COMPANY = {
  name: "CÔNG TY CỔ PHẦN CÔNG NGHỆ GREENSOFT",
  short: "GREENSOFT",
  app: "DigiHR",
}

export const CURRENT_PERIOD = "2026-09"

export const employees: Employee[] = [
  {
    id: "NS01",
    name: "Huỳnh Hoàng Bửu",
    group: "Web + Network",
    title: "Kỹ thuật Web & Network",
    baseSalary: 10_500_000,
    kpiTarget: 1_500_000,
    cksTarget: 0,
    networkEligible: true,
    initials: "HB",
  },
  {
    id: "NS02",
    name: "Nguyễn Bảo Duy",
    group: "Web + Network",
    title: "Kỹ thuật Web & Network",
    baseSalary: 10_500_000,
    kpiTarget: 1_500_000,
    cksTarget: 0,
    networkEligible: true,
    initials: "ND",
  },
  {
    id: "NS03",
    name: "Kiều Lê Hoàng Nghĩa",
    group: "Web + Network",
    title: "Kỹ thuật Web & Network",
    baseSalary: 8_000_000,
    kpiTarget: 1_000_000,
    cksTarget: 0,
    networkEligible: true,
    initials: "KN",
  },
  {
    id: "NS04",
    name: "Nguyễn Đặng Thùy Dung",
    group: "Web Operations",
    title: "QLDA Web / sửa web / hợp đồng / hỗ trợ khách",
    baseSalary: 8_000_000,
    kpiTarget: 1_000_000,
    cksTarget: 0,
    networkEligible: false,
    initials: "ND",
  },
  {
    id: "NS05",
    name: "Trương Thị Anh Hậu",
    group: "Web",
    title: "Thiết kế Web",
    baseSalary: 8_000_000,
    kpiTarget: 1_000_000,
    cksTarget: 0,
    networkEligible: false,
    initials: "TH",
  },
  {
    id: "NS06",
    name: "Lê Văn Kiệt",
    group: "CKS + Network",
    title: "Hỗ trợ chữ ký số / hỗ trợ Network",
    baseSalary: 6_000_000,
    kpiTarget: 500_000,
    cksTarget: 500_000,
    networkEligible: true,
    initials: "LK",
  },
  {
    id: "NS07",
    name: "Nguyễn Lê Thu Na",
    group: "CKS",
    title: "Chữ ký số / bán mới / gia hạn / CSKH",
    baseSalary: 8_000_000,
    kpiTarget: 500_000,
    cksTarget: 1_500_000,
    networkEligible: false,
    initials: "NN",
  },
  {
    id: "NS08",
    name: "Đỗ Minh Trung",
    group: "CKS",
    title: "Chữ ký số",
    baseSalary: 9_000_000,
    kpiTarget: 500_000,
    cksTarget: 1_000_000,
    networkEligible: false,
    initials: "DT",
  },
]

export const demoUsers: DemoUser[] = [
  ...employees.map((e) => ({
    id: e.id,
    name: e.name,
    title: e.title,
    role: "employee" as const,
    employeeId: e.id,
    initials: e.initials,
  })),
  {
    id: "QL01",
    name: "Phạm Quốc Huy",
    title: "Trưởng nhóm kỹ thuật",
    role: "manager",
    initials: "PH",
  },
  {
    id: "AD01",
    name: "Trần Minh Châu",
    title: "Kế toán lương",
    role: "admin",
    initials: "TC",
  },
]

export const seedReviews: SelfReview[] = [
  {
    employeeId: "NS01",
    period: CURRENT_PERIOD,
    highlights: [
      "Hoàn thành nâng cấp module quản lý hợp đồng web cho 3 khách (Nam Á, Minh Phát, Hòa Bình).",
      "Xử lý 12 ticket sự cố mạng và camera tại văn phòng cùng 2 điểm triển khai.",
      "Hỗ trợ bàn giao kỹ thuật dự án camera Long Thành đúng hạn cam kết.",
    ],
    issues:
      "Khách Nam Á phản hồi UAT chậm 3 ngày. Checklist bàn giao camera còn thiếu mục nghiệm thu nguồn.",
    evidenceLinks: [
      "https://docs.greensoft.vn/web/hop-dong-09-2026",
      "https://tracker.greensoft.vn/NS01-09",
    ],
    projects: [
      { code: "CM09", days: 4, role: "Trưởng nhóm" },
    ],
    selfRating: "tot",
    managerRating: null,
    managerNote: "",
    status: "pending",
    submittedAt: "2026-09-06T09:20:00+07:00",
  },
  {
    employeeId: "NS02",
    period: CURRENT_PERIOD,
    highlights: [
      "Sửa 8 lỗi giao diện và tối ưu tốc độ trang chủ cho 2 website khách SME.",
      "Thi công hỗ trợ dự án camera Long Thành 3 ngày, hoàn tất chạy thử 16 mắt.",
      "Viết hướng dẫn vận hành ngắn cho khách Minh Phát, giảm ticket lặp lại.",
    ],
    issues:
      "Còn 2 ticket CSS trên Safari chưa đóng. Tài liệu nội bộ chưa đồng bộ ảnh chụp mới.",
    evidenceLinks: ["https://tracker.greensoft.vn/NS02-09"],
    projects: [{ code: "CM09", days: 3, role: "Hỗ trợ" }],
    selfRating: "tot",
    managerRating: null,
    managerNote: "",
    status: "pending",
    submittedAt: "2026-09-07T11:05:00+07:00",
  },
  {
    employeeId: "NS03",
    period: CURRENT_PERIOD,
    highlights: [
      "Hỗ trợ thi công mạng phụ cho hồ sơ khảo sát 2 điểm mới.",
      "Cập nhật plugin bảo mật và sao lưu định kỳ 6 site WordPress.",
      "Trực hỗ trợ ngoài giờ 2 buổi khi khách go-live.",
    ],
    issues: "Chưa chủ động báo tiến độ hàng tuần. Cần ghi log công việc rõ hơn.",
    evidenceLinks: ["https://docs.greensoft.vn/ops/backup-09"],
    projects: [],
    selfRating: "tot",
    managerRating: "tot",
    managerNote: "Đúng tiến độ, giữ hệ số Tốt.",
    status: "approved",
    submittedAt: "2026-09-04T16:40:00+07:00",
    decidedAt: "2026-09-05T10:15:00+07:00",
  },
  {
    employeeId: "NS04",
    period: CURRENT_PERIOD,
    highlights: [
      "Chốt 5 hợp đồng gia hạn hosting/web và bàn giao đủ hồ sơ kế toán.",
      "Xử lý 27 ticket hỗ trợ khách, không để tồn quá 1 ngày làm việc.",
      "Soạn checklist tiếp nhận yêu cầu sửa web để giảm sót hạng mục.",
    ],
    issues:
      "2 khách muốn đổi scope giữa chừng, chưa kịp cập nhật phụ lục. Cần quy trình chốt scope rõ hơn.",
    evidenceLinks: [
      "https://crm.greensoft.vn/contracts/09-2026",
      "https://docs.greensoft.vn/ops/checklist-sua-web",
    ],
    projects: [],
    selfRating: "dat",
    managerRating: null,
    managerNote: "",
    status: "pending",
    submittedAt: "2026-09-08T08:50:00+07:00",
  },
  {
    employeeId: "NS05",
    period: CURRENT_PERIOD,
    highlights: [
      "Hoàn thiện bộ landing 3 trang cho khách thực phẩm sạch.",
      "",
      "",
    ],
    issues: "Chưa chốt palette với khách thứ hai.",
    evidenceLinks: [],
    projects: [],
    selfRating: "dat",
    managerRating: null,
    managerNote: "",
    status: "draft",
  },
  {
    employeeId: "NS06",
    period: CURRENT_PERIOD,
    highlights: [
      "Hỗ trợ kích hoạt và gia hạn 41 hồ sơ CKS, không sót deadline khách.",
      "Đi hỗ trợ network 4 ngày tại Long Thành, xử lý xong switch tầng 2.",
      "Hướng dẫn 6 khách tự cài token lần đầu qua điện thoại.",
    ],
    issues:
      "Cuối tháng còn chậm 1 ngày với 3 ticket CKS do chờ token từ nhà cung cấp.",
    evidenceLinks: ["https://cks.greensoft.vn/tickets/09-2026"],
    projects: [{ code: "CM09", days: 4, role: "Kỹ thuật chính" }],
    selfRating: "tot",
    managerRating: "dat",
    managerNote:
      "Kết quả ổn nhưng phản hồi ticket CKS cuối tháng còn chậm. Điều chỉnh xuống Đạt.",
    status: "adjusted",
    submittedAt: "2026-09-05T14:10:00+07:00",
    decidedAt: "2026-09-06T17:30:00+07:00",
  },
  {
    employeeId: "NS07",
    period: CURRENT_PERIOD,
    highlights: [
      "Bán mới 18 gói CKS và gia hạn 27 gói, vượt chỉ tiêu tháng.",
      "Gọi chăm sóc 40 khách sắp hết hạn, giữ lại 34 hợp đồng.",
      "Lập file theo dõi pipeline tuần để team CKS chủ động nhắc hạn.",
    ],
    issues: "2 khách doanh nghiệp lớn đang chờ pháp chế, chưa chốt trong tháng.",
    evidenceLinks: [
      "https://cks.greensoft.vn/sales/09-2026",
      "https://docs.greensoft.vn/cks/pipeline-t9",
    ],
    projects: [],
    selfRating: "xuat-sac",
    managerRating: "xuat-sac",
    managerNote: "Doanh số rõ, chăm sóc khách tốt. Duyệt Xuất sắc.",
    status: "approved",
    submittedAt: "2026-09-03T18:00:00+07:00",
    decidedAt: "2026-09-04T09:40:00+07:00",
  },
  {
    employeeId: "NS08",
    period: CURRENT_PERIOD,
    highlights: [
      "Xử lý 63 hồ sơ phát hành CKS, không sai thông tin MST.",
      "Hỗ trợ 11 khách gặp lỗi ký trên macOS, viết note nội bộ để team dùng lại.",
      "Phối hợp Na chốt 4 gói gia hạn khách cũ bị bỏ quên.",
    ],
    issues: "Ca chiều thứ Sáu còn ứ đọng vì thiếu máy đọc token dự phòng.",
    evidenceLinks: ["https://cks.greensoft.vn/queue/NS08-09"],
    projects: [],
    selfRating: "tot",
    managerRating: null,
    managerNote: "",
    status: "pending",
    submittedAt: "2026-09-07T17:25:00+07:00",
  },
]

export const seedCks: CksMonth = {
  period: CURRENT_PERIOD,
  target: 300_000_000,
  revenue: 315_000_000,
}

export const seedProjects: BonusProject[] = [
  {
    id: "BT08",
    code: "BT08",
    name: "Thi công Bình Thuận",
    period: "2026-08",
    pool: 6_500_000,
    participants: [
      { employeeId: "NS01", days: 5, role: "ky-thuat-chinh" },
      { employeeId: "NS02", days: 5, role: "ky-thuat-chinh" },
      { employeeId: "NS03", days: 5, role: "ho-tro" },
    ],
  },
  {
    id: "CM09",
    code: "CM09",
    name: "Thi công camera Long Thành",
    period: CURRENT_PERIOD,
    pool: 4_200_000,
    participants: [
      { employeeId: "NS01", days: 4, role: "truong-nhom" },
      { employeeId: "NS06", days: 4, role: "ky-thuat-chinh" },
      { employeeId: "NS02", days: 3, role: "ho-tro" },
    ],
  },
]

export const seedPayrollInputs: PayrollInput[] = [
  {
    employeeId: "NS01",
    period: CURRENT_PERIOD,
    workDays: 26,
    overtime: 800_000,
    allowances: 730_000,
    otherBonus: 0,
    otherBonusLabel: "",
    advance: 0,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS02",
    period: CURRENT_PERIOD,
    workDays: 25,
    overtime: 400_000,
    allowances: 730_000,
    otherBonus: 0,
    otherBonusLabel: "",
    advance: 2_000_000,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS03",
    period: CURRENT_PERIOD,
    workDays: 26,
    overtime: 0,
    allowances: 730_000,
    otherBonus: 500_000,
    otherBonusLabel: "Chuyên cần",
    advance: 0,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS04",
    period: CURRENT_PERIOD,
    workDays: 26,
    overtime: 200_000,
    allowances: 500_000,
    otherBonus: 0,
    otherBonusLabel: "",
    advance: 0,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS05",
    period: CURRENT_PERIOD,
    workDays: 24,
    overtime: 0,
    allowances: 500_000,
    otherBonus: 0,
    otherBonusLabel: "",
    advance: 0,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS06",
    period: CURRENT_PERIOD,
    workDays: 26,
    overtime: 300_000,
    allowances: 400_000,
    otherBonus: 0,
    otherBonusLabel: "",
    advance: 1_000_000,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS07",
    period: CURRENT_PERIOD,
    workDays: 26,
    overtime: 0,
    allowances: 600_000,
    otherBonus: 1_000_000,
    otherBonusLabel: "Thưởng bán mới",
    advance: 0,
    otherDeduction: 0,
    otherDeductionLabel: "",
  },
  {
    employeeId: "NS08",
    period: CURRENT_PERIOD,
    workDays: 25,
    overtime: 0,
    allowances: 500_000,
    otherBonus: 0,
    otherBonusLabel: "",
    advance: 0,
    otherDeduction: 150_000,
    otherDeductionLabel: "Đồng phục",
  },
]

export const seedPublishes: PayslipPublish[] = employees.map((e) => ({
  employeeId: e.id,
  period: CURRENT_PERIOD,
  published: e.id === "NS03" || e.id === "NS07",
}))
